### ISSUE TITLE
Enhancement - Add task to Job Queue by button like Create PDF for Job Processor

### ISSUE THREAD

**Issue by DariuszMrozik** [koechlm/Vault-Sample---Job4iLogicRuleExec#2]
It will be good if User can add task for JobProcessor manualy without change state.

**Comment by koechlm** [comment]
Great feedback; I am glad to hear that you mention this as a first requirement. It is on the roadmap already.

**Comment by koechlm** [comment]
Implemented with the latest commit. Not released yet.
