### ISSUE TITLE
Permission checking not don't work with PL version

### ISSUE THREAD

**Issue by DariuszMrozik** [koechlm/Vault-Sample---Job4iLogicRuleExec#23]
**Describe the bug**
Permission list is in Polish language. There is hard coded text. Please look on screen.
![image](https://user-images.githubusercontent.com/61918020/145571676-a4b119a6-d900-45ee-be4e-0b33c303d870.png)

You can check it on Polish environment.

**Comment by DariuszMrozik** [comment]
Tere is a message to Admin User, that we have no right permissions.

**Comment by DariuszMrozik** [comment]
Try this:
`
        public void mJobAdminHndlr(object s, CommandItemEventArgs e)
        {
            Autodesk.Connectivity.WebServices.Permis[] mAllPermisObjects = e.Context.Application.Connection.WebServiceManager.AdminService.GetPermissionsByUserId(e.Context.Application.Connection.UserID);
            if (mAllPermisObjects.Any(permis => permis.Id == 54))
            {
                mConfigPerm = true;
                iLogicJobAdminForm mAdminWindow = new iLogicJobAdminForm();
                mAdminWindow.ShowDialog();
            }
            else
            {
                MessageBox.Show("You do not have sufficient permissions to configure Vault behaviors. \n\r Contact your Vault Configuration Administrator.", "iLogic Job Administration.", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }
        }

`

**Comment by koechlm** [comment]
@DariuszMrozik: Hello Dariusz,
thank you for the heads-up. #19 is already logged for this.
Thanks,
Markus
