### ISSUE TITLE
Support for Vault 2023.1

### ISSUE THREAD

**Issue by jtbjelle** [koechlm/Vault-Sample---Job4iLogicRuleExec#29]
Are their any plans to make the extension work for vault 2023.1? We would really like to try out the extension, but the latest version of the extension doesn’t seem compatible with our version of the vault.

**Comment by koechlm** [comment]
Thank you for the heads-up. I will release an updated version targeting 2023.2. or newer.

**Comment by jtbjelle** [comment]
Nice! I am looking forward to it

**Comment by koechlm** [comment]
Hi @jtbjelle. Find the latest installable: https://github.com/koechlm/Vault-Job-Processor---iLogic-Extension/releases/tag/2023.2.0

**Comment by koechlm** [comment]
Hi @jtbjelle. Another customer found an important leak that I fixed today. If you already downloaded version 2023.2.0, please update with the latest installable: https://github.com/koechlm/Vault-Job-Processor---iLogic-Extension/releases/tag/2023.2.1
Thanks,
Markus
