### ISSUE TITLE
Password does not work for "iLogicJobExtensionSample_2024.1_Setup.7z"

### ISSUE THREAD

**Issue by mschindler96** [koechlm/Vault-Sample---Job4iLogicRuleExec#30]
**Describe the bug**
When trying to extract the downloaded "iLogicJobExtensionSample_2024.1_Setup.7z" file and using the password from the Readme "iLogicJobExtensionSample_2024.1_Setup_Disclaimer.txt", it doesn't work.
Note: The password is the same as in the previous release.

**To Reproduce**
1. Download the "iLogicJobExtensionSample_2024.1_Setup.7z" and "iLogicJobExtensionSample_2024.1_Setup_Disclaimer.txt" file from the releases.
2. Read the file "iLogicJobExtensionSample_2024.1_Setup_Disclaimer.txt"
3. Try the password for when extracting the "iLogicJobExtensionSample_2024.1_Setup.7z" file

**Expected behavior**
The right password for extracting the  "iLogicJobExtensionSample_2024.1_Setup.7z" file should be in the "iLogicJobExtensionSample_2024.1_Setup_Disclaimer.txt" file.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by koechlm** [comment]
Hi, @mschindler96, thanks for bringing this to my attention. The file updated with the correct PW.
