### ISSUE TITLE
Support for Vault 2024.2

### ISSUE THREAD

**Issue by Danieliusss** [koechlm/Vault-Sample---Job4iLogicRuleExec#33]
Hi, I appreciate your fantastic addon for Vault. However, Autodesk no longer provides installation files for Vault Client 2024.1; only the 2024.2 version is available. Is it possible to obtain an updated version of your software that supports Vault 2024.2?
Thank you!

**Comment by koechlm** [comment]
Closing this issue while publishing 2024.2 release: https://github.com/koechlm/Vault-Job-Processor---iLogic-Extension/releases/tag/2024.2
