### ISSUE TITLE
 Specified OLE variant is invalid.

### ISSUE THREAD

**Issue by cadtoolbox** [koechlm/Vault-Sample---Job4iLogicRuleExec#4]
Attempting to intertwine this example into my existing code and I receive the error on mAutomation.RunExternalRuleWithArguments as "Specified OLE variant is invalid".

What could this error be referring to?

**Comment by koechlm** [comment]
Your "existing" code is an iLogic rule running properly in Inventor, right? Mind that ThisApp (Inventor.exe) and ThisServer (InventorServer.exe) don't have identical API access. Did you establish rule logging to investigate the rule execution? We also could step into the rule code, but I think I need to deliver more detailed documentation on how to do this. It is on the roadmap for April.

**Comment by koechlm** [comment]
closing the issue due to missing feedback.
