### ISSUE TITLE
Undo Check Out on Error

### ISSUE THREAD

**Issue by DariuszMrozik** [koechlm/Vault-Sample---Job4iLogicRuleExec#5]
It will be good if on error with extension, there is undocheckout of file.

**Comment by koechlm** [comment]
it is implemented for both: failure on external rules and failed internal rules. The key is, that your rules have to throw exceptions in case of errors. This is something to be written differently for Inventor and VaultInventorServer Job executed rules.
Did you encounter a scenario that checked out a file but the job failed for other reasons than an iLogic error? If so, let me know the steps to reproduce.
thanks,
Markus

**Comment by koechlm** [comment]
@DariuszMrozik: can you share any news on this from your side? 
Thanks,
Markus

**Comment by DariuszMrozik** [comment]
I can't reproduce that now. It was caused because the logger config wasn't input in bin folder I think.

**Comment by koechlm** [comment]
Thanks for the feedback.
